# CodeRabbit Configuration
# MINIMAL NOISE MODE - Only critical security/bug issues

# Enable manual trigger only - disable automatic reviews
enabled: false  # Set to true only when you want reviews

# Review Settings
reviews:
  # Only comment on CRITICAL issues
  comment_threshold: "critical"
  
  # Disable auto-review for certain file types
  ignore_patterns:
    - "*.md"
    - "*.json"
    - "*.yml"
    - "*.yaml"
    - "*.txt"
    - "*.log"
    - "tests/**"
    - "docs/**"
    - "*.test.*"
    - "*.spec.*"
  
  # Focus areas - only review these aspects
  focus_areas:
    - "security"
    - "performance"
    - "logic_errors"
    - "potential_bugs"
  
  # Skip style and formatting issues (handled by linters)
  skip_checks:
    - "code_style"
    - "naming_conventions"
    - "documentation"
    - "whitespace"
    - "line_length"

# Summary Settings  
summary:
  # Keep summaries concise
  style: "concise"
  
  # Only include critical findings in summary
  include_only_critical: true
  
  # Max length for summary comments
  max_length: 500

# Behavior Settings
behavior:
  # Don't comment on every file change
  file_comment_limit: 3
  
  # Group related issues into single comment
  group_related_issues: true
  
  # Don't re-comment on resolved conversations
  skip_resolved: true
  
  # Minimal interaction mode
  interaction_mode: "minimal"

# Language-specific settings
languages:
  python:
    # Focus on actual bugs, not style
    checks:
      - "undefined_variables"
      - "type_errors"
      - "logic_errors"
      - "security_issues"
  
  javascript:
    checks:
      - "undefined_variables"
      - "type_errors"
      - "async_issues"
      - "security_issues"

# Disable features that create noise
disable:
  - "emoji_reactions"
  - "praise_comments"
  - "nitpick_mode"
  - "style_suggestions"
  - "refactoring_suggestions"

# Email notification settings
notifications:
  email: false

# HOW TO STOP CODERABBIT EMAILS:
# 1. This config disables automatic reviews (enabled: false above)
# 2. To stop GitHub notification emails:
#    - Go to: https://github.com/settings/notifications
#    - Find "Watching" section
#    - Change to "Participating" or "Custom"
#    - Or unwatch specific repos
# 3. To trigger CodeRabbit manually when needed:
#    - Comment "@coderabbitai review" on any PR
# 4. To disable CodeRabbit completely:
#    - Go to repo Settings > Integrations > CodeRabbit
#    - Click "Configure" and remove access