version = 1

# DISABLED: DeepSource is creating PRs with syntax errors
# The auto-formatters (autopep8, black, isort) are conflicting
# and breaking our code. Re-enable only after proper testing.

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = false

[[analyzers]]
name = "secrets"
enabled = false  # Disabled - conflicts with other security tools

# TRANSFORMERS DISABLED - They break our code
# [[transformers]]
# name = "autopep8"
# enabled = false

# [[transformers]]
# name = "isort"
# enabled = false

# [[transformers]]
# name = "black"
# enabled = false