version: '3.8'
services:
  mcp-server:
    image: ghcr.io/github/github-mcp-server:latest
    ports:
      - "8080:8080"
    environment:
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_APP_PRIVATE_KEY_PATH=/app/github-app-private-key.pem
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ~/.ssh/github-mcp-orchestrator.private-key.pem:/app/github-app-private-key.pem:ro
    command: server http
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
