name: Badge Validation Workflow
description: Orchestration workflow to validate README badges and prevent fake placeholders

triggers:
  - commit
  - pull_request
  - manual

agents:
  - name: badge-validator
    type: reviewer
    capabilities:
      - badge_analysis
      - url_validation
      - fake_detection
    
workflow:
  steps:
    - name: validate_badges
      agent: badge-validator
      task: |
        Run comprehensive badge validation on README.md:
        1. Extract all badges from README
        2. Check for fake/placeholder terms ("unknown", "100%", "ready", etc.)
        3. Validate all badge URLs are accessible
        4. Verify badges link to real services (not generic shields.io)
        5. Flag any static badges with made-up numbers
        6. Generate actionable recommendations
      
    - name: memory_store
      task: |
        Store validation results in Memory with key "badge_validation"
        Include timestamp and detailed findings
        
    - name: report_findings
      task: |
        Generate Slack notification if issues found:
        - List specific fake badges detected
        - Show broken URLs
        - Provide fix recommendations
        - Prevent commit if critical issues found

validation_rules:
  forbidden_terms:
    - "unknown"
    - "generated by tests" 
    - "sonarcloud ready"
    - "placeholder"
    - "100%"
    - "95%"
    
  required_real_services:
    - codecov_badge: "codecov.io"
    - sonar_badge: "sonarcloud.io"
    - tests_badge: "github.com/*/workflows/*"
    
  auto_actions:
    fake_detected: "block_commit"
    broken_urls: "warn"
    missing_services: "suggest_setup"