AWSTemplateFormatVersion: '2010-09-09'
Description: 'Autonomous Orchestration Infrastructure - Core Components Only'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Environment name

  GitHubToken:
    Type: String
    NoEcho: true
    Description: GitHub Personal Access Token

  SlackWebhookURL:
    Type: String
    NoEcho: true
    Description: Slack Webhook URL for notifications

  SentryDSN:
    Type: String
    NoEcho: true
    Default: ""
    Description: Sentry DSN for error tracking

  SentryAuthToken:
    Type: String
    NoEcho: true
    Default: ""
    Description: Sentry Auth Token for API access

Resources:
  # DynamoDB Tables for Configuration and Logging
  ConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'kindlemint-config-${Environment}'
      BillingMode: PAY_PER_REQUEST  # Cost-optimized for low usage
      AttributeDefinitions:
        - AttributeName: config_type
          AttributeType: S
      KeySchema:
        - AttributeName: config_type
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: autonomous-orchestration

  OrchestrationLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'kindlemint-orchestration-logs-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: log_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: log_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: timestamp-index
          KeySchema:
            - AttributeName: timestamp
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true  # Auto-cleanup old logs to save costs
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: autonomous-orchestration

  # Secrets Manager for secure credential storage
  GitHubTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/kindlemint/${Environment}/github-token'
      Description: 'GitHub Personal Access Token'
      SecretString: !Ref GitHubToken

  SlackWebhookSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/kindlemint/${Environment}/slack-webhook'
      Description: 'Slack Webhook URL'
      SecretString: !Ref SlackWebhookURL

  SentrySecretsGroup:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/kindlemint/${Environment}/sentry-config'
      Description: 'Sentry Configuration'
      SecretString: !Sub |
        {
          "dsn": "${SentryDSN}",
          "auth_token": "${SentryAuthToken}"
        }

  # SNS Topic for notifications
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'kindlemint-orchestration-notifications-${Environment}'
      DisplayName: 'KindleMint Orchestration Notifications'

  # Dead Letter Queue for failed executions
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'kindlemint-orchestration-dlq-${Environment}'
      MessageRetentionPeriod: 1209600  # 14 days
      VisibilityTimeoutSeconds: 300

  # Cost Control: Billing Alarm
  BillingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'kindlemint-orchestration-billing-${Environment}'
      AlarmDescription: 'Billing alarm for orchestration system'
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Statistic: Maximum
      Period: 86400  # Daily
      EvaluationPeriods: 1
      Threshold: 20  # $20/month threshold
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Currency
          Value: USD
      AlarmActions:
        - !Ref NotificationTopic

Outputs:
  ConfigTableName:
    Description: 'Configuration DynamoDB Table Name'
    Value: !Ref ConfigTable
    Export:
      Name: !Sub '${AWS::StackName}-config-table-name'

  OrchestrationLogsTableName:
    Description: 'Orchestration Logs DynamoDB Table Name'
    Value: !Ref OrchestrationLogsTable
    Export:
      Name: !Sub '${AWS::StackName}-logs-table-name'

  NotificationTopicArn:
    Description: 'SNS Notification Topic ARN'
    Value: !Ref NotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-notification-topic-arn'

  GitHubTokenSecretArn:
    Description: 'GitHub Token Secret ARN'
    Value: !Ref GitHubTokenSecret
    Export:
      Name: !Sub '${AWS::StackName}-github-token-secret-arn'

  SlackWebhookSecretArn:
    Description: 'Slack Webhook Secret ARN'
    Value: !Ref SlackWebhookSecret
    Export:
      Name: !Sub '${AWS::StackName}-slack-webhook-secret-arn'

  DeadLetterQueueArn:
    Description: 'Dead Letter Queue ARN'
    Value: !GetAtt DeadLetterQueue.Arn
    Export:
      Name: !Sub '${AWS::StackName}-dlq-arn'

  EstimatedMonthlyCost:
    Description: 'Estimated monthly cost for infrastructure'
    Value: '$2-8 (DynamoDB + Secrets Manager + SNS)'

  InfrastructureStatus:
    Description: 'Infrastructure deployment status'
    Value: 'Core infrastructure deployed successfully - Lambda functions can be added separately'