AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal AWS Infrastructure for KindleMint Orchestration'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Environment name

Resources:
  # DynamoDB Table for Configuration
  ConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'kindlemint-config-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: config_type
          AttributeType: S
      KeySchema:
        - AttributeName: config_type
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: autonomous-orchestration

  # DynamoDB Table for Logs
  OrchestrationLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'kindlemint-orchestration-logs-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: log_id
          AttributeType: S
      KeySchema:
        - AttributeName: log_id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: autonomous-orchestration

  # SNS Topic for notifications
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'kindlemint-orchestration-notifications-${Environment}'
      DisplayName: 'KindleMint Orchestration Notifications'

Outputs:
  ConfigTableName:
    Description: 'Configuration DynamoDB Table Name'
    Value: !Ref ConfigTable
    Export:
      Name: !Sub '${AWS::StackName}-config-table-name'

  OrchestrationLogsTableName:
    Description: 'Orchestration Logs DynamoDB Table Name'
    Value: !Ref OrchestrationLogsTable
    Export:
      Name: !Sub '${AWS::StackName}-logs-table-name'

  NotificationTopicArn:
    Description: 'SNS Notification Topic ARN'
    Value: !Ref NotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-notification-topic-arn'

  StackStatus:
    Description: 'Infrastructure deployment status'
    Value: 'SUCCESS - Core AWS infrastructure deployed'

  CostEstimate:
    Description: 'Estimated monthly cost'
    Value: '$1-3 per month for DynamoDB + SNS'
