model_selection:
  primary_content:
    model: claude-3.5-sonnet
    use_cases:
      - Creative writing
      - Complex narratives
      - Technical accuracy
  specialized_tasks:
    code_generation: deepseek-coder-v2
    market_analysis: qwen-3-72b
    translation: opus-multilingual
    summarization: mistral-medium
