"""
Tests for MarketingSpecialistAgent
Generated by Claude Code Orchestrator
"""

import pytest

# Skip the entire module during the transition away from legacy agent tests.
pytest.skip("agent tests deprecated", allow_module_level=True)

import sys
from pathlib import Path

import pytest

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

MarketingSpecialistAgent = __import__(
    "marketing-specialist_agent"
).MarketingSpecialistAgent


class TestMarketingSpecialistAgent:
    """Test suite for MarketingSpecialistAgent"""

    @pytest.fixture
    def agent(self):
        """Create agent instance for testing"""
        return MarketingSpecialistAgent()

    def test_initialization(self, agent):
        """Test agent initialization"""
        assert agent is not None
        assert agent.capabilities == ["market-analysis"]

    @pytest.mark.asyncio
    async def test_execute_valid_task(self, agent):
        """Test executing a valid task"""
        result = await agent.execute("market-analysis", {})
        assert result["status"] == "success"
        assert result["capability"] == "market-analysis"

    @pytest.mark.asyncio
    async def test_execute_invalid_task(self, agent):
        """Test executing an invalid task"""
        result = await agent.execute("invalid-task", {})
        assert result["status"] == "error"
        assert "Unknown task" in result["message"]


@pytest.mark.asyncio
async def test_market_analysis(self, agent):
    """Test market analysis capability"""
    result = await agent.market_analysis()
    assert result["status"] == "success"
    assert result["capability"] == "market-analysis"
