"""
Tests for ContentGeneratorAgent
Generated by Claude Code Orchestrator
"""

import pytest

# Skip the entire module during the transition away from legacy agent tests.
pytest.skip("agent tests deprecated", allow_module_level=True)

import pytest
import asyncio
from pathlib import Path
import sys

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

ContentGeneratorAgent = __import__("content-generator_agent").ContentGeneratorAgent


class TestContentGeneratorAgent:
    """Test suite for ContentGeneratorAgent"""

    @pytest.fixture
    def agent(self):
        """Create agent instance for testing"""
        return ContentGeneratorAgent()

    def test_initialization(self, agent):
        """Test agent initialization"""
        assert agent is not None
        assert agent.capabilities == ['content-generation', 'seo-optimization']

    @pytest.mark.asyncio
    async def test_execute_valid_task(self, agent):
        """Test executing a valid task"""
        result = await agent.execute("content-generation", {})
        assert result["status"] == "success"
        assert result["capability"] == "content-generation"

    @pytest.mark.asyncio
    async def test_execute_invalid_task(self, agent):
        """Test executing an invalid task"""
        result = await agent.execute("invalid-task", {})
        assert result["status"] == "error"
        assert "Unknown task" in result["message"]

@pytest.mark.asyncio
async def test_content_generation(self, agent):
    """Test content generation capability"""
    result = await agent.content_generation()
    assert result["status"] == "success"
    assert result["capability"] == "content-generation"


@pytest.mark.asyncio
async def test_seo_optimization(self, agent):
    """Test seo optimization capability"""
    result = await agent.seo_optimization()
    assert result["status"] == "success"
    assert result["capability"] == "seo-optimization"
