name: Auto-Merge PRs with MCP

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      statuses: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install MCP GitHub Server
        run: |
          npm install -g @modelcontextprotocol/server-github
          npm install -g @anthropic-ai/sdk

      - name: Analyze PR with MCP
        id: analyze
        run: |
          echo "Analyzing PR #${{ github.event.pull_request.number }}"
          
          # Use MCP to analyze the PR
          mcp-github analyze-pr \
            --repo="${{ github.repository }}" \
            --pr="${{ github.event.pull_request.number }}" \
            --token="${{ secrets.GITHUB_TOKEN }}" \
            --output=pr-analysis.json
          
          # Check if PR is ready for merge
          if [ -f "pr-analysis.json" ]; then
            echo "PR analysis completed"
            echo "ready_for_merge=true" >> $GITHUB_OUTPUT
          else
            echo "PR analysis failed"
            echo "ready_for_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Auto-approve PR
        if: steps.analyze.outputs.ready_for_merge == 'true'
        run: |
          echo "Auto-approving PR #${{ github.event.pull_request.number }}"
          
          # Use GitHub CLI to approve the PR
          gh pr review ${{ github.event.pull_request.number }} --approve --body "✅ Auto-approved by MCP bot - PR meets all requirements for merge"

      - name: Enable auto-merge
        if: steps.analyze.outputs.ready_for_merge == 'true'
        run: |
          echo "Enabling auto-merge for PR #${{ github.event.pull_request.number }}"
          
          # Enable auto-merge
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash

      - name: Comment on PR
        if: always()
        run: |
          if [ "${{ steps.analyze.outputs.ready_for_merge }}" == "true" ]; then
            gh pr comment ${{ github.event.pull_request.number }} --body "🤖 **MCP Bot Report**\n\n✅ **Status**: Ready for merge\n✅ **Auto-approval**: Applied\n✅ **Auto-merge**: Enabled\n\nThis PR has been automatically approved and will be merged when all checks pass."
          else
            gh pr comment ${{ github.event.pull_request.number }} --body "🤖 **MCP Bot Report**\n\n⚠️ **Status**: Requires manual review\n\nThis PR needs additional review before it can be merged."
          fi

      - name: Handle merge conflicts
        if: failure()
        run: |
          echo "Handling merge conflicts for PR #${{ github.event.pull_request.number }}"
          gh pr comment ${{ github.event.pull_request.number }} --body "🤖 **MCP Bot Report**\n\n❌ **Status**: Merge conflict detected\n\nPlease resolve conflicts and update the PR." 