name: Automated Traffic Generation (FREE)

on:
  schedule:
    # Run daily at 9 AM UTC (helps with SEO freshness)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-seo-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate programmatic SEO pages
        run: |
          # Create SEO-optimized pages for long-tail keywords
          mkdir -p landing-pages/sudoku-for-seniors/pages/puzzles
          
          # Generate city-specific pages (high search volume)
          cities=("new-york" "los-angeles" "chicago" "houston" "phoenix" "philadelphia" "san-antonio" "san-diego" "dallas" "san-jose")
          difficulties=("easy" "medium" "hard" "expert")
          
          for city in "${cities[@]}"; do
            for difficulty in "${difficulties[@]}"; do
              page_file="landing-pages/sudoku-for-seniors/pages/puzzles/${difficulty}-sudoku-${city}.tsx"
              
              cat > "$page_file" << EOF
          import Head from 'next/head';
          import Link from 'next/link';
          
          export default function ${difficulty^}Sudoku${city^//-}() {
            const cityName = "${city}".replace('-', ' ').replace(/\b\w/g, l => l.toUpperCase());
            const difficulty = "${difficulty}";
            
            return (
              <>
                <Head>
                  <title>{difficulty^} Large Print Sudoku for Seniors in {cityName} | Free Puzzles</title>
                  <meta name="description" content="Free {difficulty} large print Sudoku puzzles for seniors 75+ in {cityName}. Easy on the eyes, perfect for brain training." />
                  <meta name="keywords" content="sudoku {cityName}, large print puzzles {cityName}, seniors brain games {cityName}, {difficulty} sudoku" />
                </Head>
                
                <div className="min-h-screen bg-gray-50 py-12">
                  <div className="container mx-auto px-6">
                    <h1 className="text-4xl font-bold text-center mb-8">
                      {difficulty^} Large Print Sudoku for Seniors in {cityName}
                    </h1>
                    
                    <div className="max-w-4xl mx-auto">
                      <div className="bg-white rounded-lg shadow-lg p-8 mb-8">
                        <h2 className="text-2xl font-semibold mb-4">Perfect for {cityName} Seniors</h2>
                        <p className="text-lg text-gray-700 mb-6">
                          Enjoy {difficulty} Sudoku puzzles designed specifically for seniors in {cityName}. 
                          Our large print format makes solving comfortable and enjoyable.
                        </p>
                        
                        <div className="grid md:grid-cols-2 gap-6 mb-8">
                          <div>
                            <h3 className="font-semibold mb-2">Why {cityName} Seniors Love Our Puzzles:</h3>
                            <ul className="list-disc list-inside space-y-1 text-gray-700">
                              <li>Extra-large 20+ point fonts</li>
                              <li>High contrast for easy reading</li>
                              <li>Perfect for aging eyes</li>
                              <li>{difficulty^} difficulty level</li>
                            </ul>
                          </div>
                          <div>
                            <h3 className="font-semibold mb-2">Brain Health Benefits:</h3>
                            <ul className="list-disc list-inside space-y-1 text-gray-700">
                              <li>Improves memory and focus</li>
                              <li>Enhances problem-solving skills</li>
                              <li>Provides mental stimulation</li>
                              <li>Reduces cognitive decline risk</li>
                            </ul>
                          </div>
                        </div>
                        
                        <div className="text-center">
                          <Link href="/" className="bg-blue-600 text-white px-8 py-4 rounded-lg font-semibold text-lg hover:bg-blue-700 transition">
                            Get 5 FREE Large Print Sudoku Puzzles →
                          </Link>
                        </div>
                      </div>
                      
                      <div className="bg-blue-50 rounded-lg p-6">
                        <h3 className="text-xl font-semibold mb-4">More {difficulty^} Puzzles for {cityName} Residents</h3>
                        <p className="text-gray-700 mb-4">
                          Join thousands of {cityName} seniors who start their day with mental exercise. 
                          Our puzzles are designed by experts and tested by seniors just like you.
                        </p>
                        <Link href="/" className="text-blue-600 hover:text-blue-800 font-semibold">
                          Download your free puzzles now →
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              </>
            );
          }
          EOF
            done
          done

      - name: Generate sitemap
        run: |
          # Create sitemap for all generated pages
          sitemap_file="landing-pages/sudoku-for-seniors/public/sitemap.xml"
          
          cat > "$sitemap_file" << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          EOF
          
          # Add main pages
          echo "  <url><loc>https://sudokufor75plus.com/</loc><priority>1.0</priority></url>" >> "$sitemap_file"
          
          # Add all generated city/difficulty pages
          for file in landing-pages/sudoku-for-seniors/pages/puzzles/*.tsx; do
            if [ -f "$file" ]; then
              page_name=$(basename "$file" .tsx)
              echo "  <url><loc>https://sudokufor75plus.com/puzzles/$page_name</loc><priority>0.8</priority></url>" >> "$sitemap_file"
            fi
          done
          
          echo "</urlset>" >> "$sitemap_file"

      - name: Generate robots.txt
        run: |
          cat > "landing-pages/sudoku-for-seniors/public/robots.txt" << 'EOF'
          User-agent: *
          Allow: /
          
          Sitemap: https://sudokufor75plus.com/sitemap.xml
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Auto-generate SEO content for $(date +%Y-%m-%d)"
            git push
          fi

  submit-to-search-engines:
    runs-on: ubuntu-latest
    needs: generate-seo-content
    steps:
      - name: Ping Google
        run: |
          # Notify Google of sitemap updates (free)
          curl -X GET "https://www.google.com/ping?sitemap=https://sudokufor75plus.com/sitemap.xml"
          
      - name: Ping Bing
        run: |
          # Notify Bing of sitemap updates (free)
          curl -X GET "https://www.bing.com/ping?sitemap=https://sudokufor75plus.com/sitemap.xml"

  social-sharing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-post to dev.to (FREE)
        env:
          DEV_TO_API_KEY: ${{ secrets.DEV_TO_API_KEY }}
        run: |
          # Create a dev.to article about Sudoku tips (brings traffic)
          if [ -n "$DEV_TO_API_KEY" ]; then
            curl -X POST "https://dev.to/api/articles" \
              -H "Content-Type: application/json" \
              -H "api-key: $DEV_TO_API_KEY" \
              -d '{
                "article": {
                  "title": "5 Sudoku Tips That Changed My Life at 75",
                  "published": true,
                  "body_markdown": "# Brain Training at Any Age\n\nAs someone who discovered Sudoku at 75, I want to share the tips that made all the difference...\n\n## Tip 1: Use Large Print\nThe biggest game-changer was finding **large print** Sudoku books. No more squinting!\n\n## Tip 2: Start with Easy\nDon'\''t rush into hard puzzles. Build confidence with easy ones first.\n\n## Tip 3: Use a Pencil\nMistakes are part of learning. Use pencil and eraser freely.\n\n## Tip 4: Take Breaks\nYour brain needs rest. 15-20 minute sessions are perfect.\n\n## Tip 5: Be Patient\nEvery expert was once a beginner. Enjoy the journey!\n\n---\n\n*Want to try? Get 5 FREE large print Sudoku puzzles designed for seniors: [sudokufor75plus.com](https://sudokufor75plus.com)*",
                  "tags": ["seniors", "brain", "puzzles", "health"],
                  "canonical_url": "https://sudokufor75plus.com/blog/sudoku-tips-seniors"
                }
              }'
          fi

  analytics-tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Log traffic generation
        run: |
          echo "Traffic generation completed: $(date)"
          echo "Pages generated: $(find landing-pages/sudoku-for-seniors/pages/puzzles -name "*.tsx" | wc -l)"
          echo "SEO potential: High (targeting 40 city+difficulty combinations)"