name: Branch Hygiene Cleanup

on:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggers

permissions:
  contents: write
  pull-requests: read

jobs:
  cleanup-branches:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run branch cleanup
        run: |
          echo "🧹 Starting branch cleanup..."
          python scripts/automated_branch_cleanup.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Report cleanup results
        if: always()
        run: |
          echo "## 📊 Branch Cleanup Summary" >> $GITHUB_STEP_SUMMARY
          echo "Cleanup completed at $(date)" >> $GITHUB_STEP_SUMMARY
