name: Claude Code PR Assistant

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  claude-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Claude Code Review
        uses: anthropic/claude-github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.CLAUDE_API_KEY }}
          # Optionally, configure Claude's behavior:
          # trigger-comment: "/claude-review"
          # model: "claude-3-opus-20240229"
          # max-tokens: 4096
