name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check Basic Environment
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Event: ${{ github.event_name }}"
        echo "Actor: ${{ github.actor }}"

    - name: Test GitHub Token
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ -n "$GITHUB_TOKEN" ]; then
          echo "✅ GITHUB_TOKEN is set"
          echo "Token length: ${#GITHUB_TOKEN}"
        else
          echo "❌ GITHUB_TOKEN is not set"
        fi

    - name: Test Slack Webhook
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        if [ -n "$SLACK_WEBHOOK_URL" ]; then
          echo "✅ SLACK_WEBHOOK_URL is set"
          echo "URL length: ${#SLACK_WEBHOOK_URL}"
        else
          echo "❌ SLACK_WEBHOOK_URL is not set"
        fi

    - name: Test Sentry Token
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      run: |
        if [ -n "$SENTRY_AUTH_TOKEN" ]; then
          echo "✅ SENTRY_AUTH_TOKEN is set"
          echo "Token length: ${#SENTRY_AUTH_TOKEN}"
        else
          echo "❌ SENTRY_AUTH_TOKEN is not set"
        fi
