name: Disable Complex Autonomous Workflows

on:
  workflow_dispatch:

jobs:
  disable-workflows:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Disable failing autonomous workflows
        uses: actions/github-script@v7
        with:
          script: |
            const workflowsToDisable = [
              '🤖 Autonomous CI Orchestration',
              '🤖 Autonomous System',
              '🤖 Autonomous Orchestration System',
              '🚀 Working Autonomous System',
              '🤖 Autonomous System - FINAL',
              '🧪 Test Autonomous Orchestration'
            ];
            
            for (const workflowName of workflowsToDisable) {
              try {
                const workflows = await github.rest.actions.listRepoWorkflows({
                  owner: context.repo.owner,
                  repo: context.repo.repo
                });
                
                const workflow = workflows.data.workflows.find(w => w.name === workflowName);
                if (workflow && workflow.state === 'active') {
                  await github.rest.actions.disableWorkflow({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    workflow_id: workflow.id
                  });
                  console.log(`✅ Disabled: ${workflowName}`);
                }
              } catch (error) {
                console.log(`⚠️ Could not disable ${workflowName}: ${error.message}`);
              }
            }
            
            console.log('✅ Disabled complex autonomous workflows');
            console.log('✅ Keeping simple workflows: Autonomous PR Handler, Issue Auto Cleanup');