name: Feature Branch Auto-Fixer

on:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  push:
    branches-ignore:
      - main
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to fix'
        required: false
        default: ''

permissions:
  contents: write
  actions: read

jobs:
  fix-feature-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Detect and fix common issues
        run: |
          echo "🔧 Fixing feature branch: ${{ github.ref_name }}"
          
          # Fix 1: Clean up Python cache files
          find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
          find . -name "*.pyc" -delete 2>/dev/null || true
          
          # Fix 2: Ensure all __init__.py files exist
          find . -type d -name "tests" -o -name "src" -o -name "scripts" | while read dir; do
            if [ ! -f "$dir/__init__.py" ]; then
              touch "$dir/__init__.py"
              echo "Created missing __init__.py in $dir"
            fi
          done
          
          # Fix 3: Fix common import errors
          if [ -f "setup.py" ]; then
            pip install -e . || echo "Setup.py installation failed"
          fi
          
          # Fix 4: Update requirements if needed
          if [ -f "requirements.txt" ]; then
            # Remove duplicates and sort
            sort -u requirements.txt -o requirements.txt
          fi
          
          # Check if any changes were made
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            
            git add -A
            git commit -m "fix: Auto-fix common issues on feature branch
            
            - Removed Python cache files
            - Added missing __init__.py files
            - Fixed requirements.txt
            
            [skip ci]"
            
            git push
            echo "✅ Fixes applied and pushed"
          else
            echo "✅ No issues found to fix"
          fi
      
      - name: Run basic validation
        continue-on-error: true
        run: |
          # Basic Python syntax check
          python -m py_compile $(find . -name "*.py" -type f) || echo "Some Python files have syntax errors"
          
      - name: Report status
        if: failure()
        run: |
          echo "⚠️ Feature branch still has issues after auto-fix attempt"
          echo "Manual intervention may be required"
