name: KDP Metadata Validation

on:
  push:
    paths:
      - '**/kdp_metadata*.json'
      - '**/amazon_kdp_metadata.json'
      - 'books/**/*.json'
  pull_request:
    paths:
      - '**/kdp_metadata*.json'
      - '**/amazon_kdp_metadata.json'
      - 'books/**/*.json'
  workflow_dispatch:

jobs:
  validate-kdp-metadata:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Validate KDP Metadata
        id: validate
        run: |
          echo "🔍 Validating all KDP metadata files..."
          python scripts/kdp_metadata_validator.py || {
            echo "validation_failed=true" >> $GITHUB_OUTPUT
            exit 1
          }
      
      - name: Check for missing categories
        if: always()
        run: |
          # Additional check specifically for 3 categories
          echo "🏷️ Checking category optimization..."
          
          find . -name "*kdp_metadata*.json" -o -name "amazon_kdp_metadata.json" | while read file; do
            CATEGORY_COUNT=$(jq '.categories | length' "$file" 2>/dev/null || echo 0)
            
            if [ "$CATEGORY_COUNT" -lt 3 ]; then
              echo "❌ $file: Only $CATEGORY_COUNT categories (KDP allows 3!)"
              echo "   Missing $(( 3 - CATEGORY_COUNT )) category slots = reduced discoverability"
            else
              echo "✅ $file: Using all 3 category slots"
            fi
          done
      
      - name: Create optimization report
        if: failure()
        run: |
          cat > kdp_optimization_report.md << 'EOF'
          # KDP Metadata Optimization Report
          
          ## ❌ Critical Issues Found
          
          ### Missing Category Slots
          KDP allows 3 categories for maximum discoverability, but some books aren't using all slots.
          
          **Impact**: Each missing category = 33% less discoverability opportunity
          
          ### Recommended Categories for Puzzle Books:
          1. Games & Activities / Sudoku (or specific puzzle type)
          2. Games & Activities / Puzzles  
          3. Games & Activities / Logic & Brain Teasers
          
          Alternative 3rd categories:
          - SELF-HELP / Aging
          - HEALTH & FITNESS / Mental Health
          - GAMES / Trivia
          
          ### Action Required:
          Update all KDP metadata files to use 3 categories for maximum visibility.
          
          ---
          Generated by KDP Metadata Validator
          EOF
          
          # Post as PR comment if in PR
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            gh pr comment ${{ github.event.pull_request.number }} --body-file kdp_optimization_report.md
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}