name: Minimal Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    timeout-minutes: 30
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install and test
      run: |
        pip install pytest
        pytest tests/test_basic.py -v
