name: PR Auto Manager

on:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  pull_request:
    types: [opened, labeled]
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:

jobs:
  auto-close-bot-prs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    permissions:
      pull-requests: write
    steps:
      - name: Close stale bot PRs
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            
            const botNames = ['seer-by-sentry[bot]', 'gowebdot[bot]', 'app/seer-by-sentry'];
            const now = new Date();
            
            for (const pr of prs) {
              if (botNames.includes(pr.user.login)) {
                const prAge = (now - new Date(pr.created_at)) / 1000 / 60 / 60; // hours
                
                // Check for human interaction
                const { data: comments } = await github.rest.issues.listComments({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number
                });
                
                const hasHumanComment = comments.some(c => !c.user.login.endsWith('[bot]'));
                
                if (prAge > 24 && !hasHumanComment && pr.draft) {
                  await github.rest.pulls.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    state: 'closed'
                  });
                  
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    body: 'Auto-closing bot-generated PR due to no human interaction after 24 hours.'
                  });
                }
              }
            }
  
  auto-merge-approved:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.pull_request.user.login == 'deepsource-autofix[bot]' || github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge for approved bot PRs
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            
            // Check if PR is approved
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            
            const isApproved = reviews.some(r => r.state === 'APPROVED');
            
            if (isApproved) {
              // Enable auto-merge
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
            }
