name: QA Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qa_checks:
    name: Run QA Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run end-to-end pipeline tests
        run: pytest tests/test_end_to_end_pipeline.py

      - name: Upload system integration test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: system_integration_test_report
          path: system_integration_test_report.json
