name: QA Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  qa_checks:
    name: Run QA Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install pinned runtime and development dependencies
          pip install --require-hashes -r requirements-locked.txt
          pip install -r requirements-dev.txt

      - name: Install Playwright Browsers
        run: |
          # Install system dependencies first
          sudo apt-get update
          sudo apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libatspi2.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2t64 libxss1 libgtk-3-0
          # Install Playwright browsers
          python -m playwright install chromium
      
      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run end-to-end pipeline tests
        run: pytest tests/test_end_to_end_pipeline.py

      - name: Upload system integration test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: system_integration_test_report
          path: system_integration_test_report.json
