name: Check Skip Conditions

on:
  workflow_call:
    outputs:
      should_skip:
        description: 'Whether to skip checks'
        value: ${{ jobs.check.outputs.should_skip }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip.outputs.should_skip }}
    steps:
      - name: Check skip conditions
        id: skip
        run: |
          # Skip for bots
          if [[ "${{ github.actor }}" == *"[bot]" ]]; then
            echo "should_skip=true" >> $GITHUB_OUTPUT
            echo "Skipping checks for bot: ${{ github.actor }}"
            exit 0
          fi
          
          # Skip for doc-only changes
          if [[ -n "${{ github.event.pull_request.title }}" ]]; then
            if [[ "${{ github.event.pull_request.title }}" == *"[skip ci]"* ]]; then
              echo "should_skip=true" >> $GITHUB_OUTPUT
              echo "Skipping due to [skip ci] in title"
              exit 0
            fi
          fi
          
          echo "should_skip=false" >> $GITHUB_OUTPUT
