name: Unified Intelligent Scheduler
on:
  schedule:
    - cron: '0 * * * *'  # Every hour (reduced from multiple 5-min schedules)
  workflow_dispatch:
    inputs:
      force_all:
        description: 'Run all scheduled tasks immediately'
        required: false
        type: boolean
        default: false

concurrency:
  group: scheduler-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: write

jobs:
  smart-dispatch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up dispatch environment
      id: setup
      run: |
        echo "HOUR=$(date +%H)" >> $GITHUB_OUTPUT
        echo "MINUTE=$(date +%M)" >> $GITHUB_OUTPUT
        echo "DAY=$(date +%u)" >> $GITHUB_OUTPUT
        echo "DAY_OF_MONTH=$(date +%d)" >> $GITHUB_OUTPUT
        
    - name: Dispatch workflows based on schedule
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        HOUR=${{ steps.setup.outputs.HOUR }}
        MINUTE=${{ steps.setup.outputs.MINUTE }}
        DAY=${{ steps.setup.outputs.DAY }}
        DAY_OF_MONTH=${{ steps.setup.outputs.DAY_OF_MONTH }}
        FORCE_ALL=${{ inputs.force_all }}
        
        echo "📅 Current time: Hour=$HOUR, Day=$DAY"
        
        # Function to conditionally run workflows
        run_workflow() {
          local workflow=$1
          local condition=$2
          
          if [ "$FORCE_ALL" == "true" ] || [ "$condition" == "true" ]; then
            echo "🚀 Dispatching $workflow"
            gh workflow run "$workflow" --ref main || echo "⚠️ Failed to dispatch $workflow"
          fi
        }
        
        # Every hour tasks
        run_workflow "pr-resolver.yml" "true"
        run_workflow "health-monitor.yml" "true"
        
        # Every 2 hours
        EVERY_2H=$([[ $((10#$HOUR % 2)) -eq 0 ]] && echo "true" || echo "false")
        run_workflow "auto-merger.yml" "$EVERY_2H"
        run_workflow "pr-labeler.yml" "$EVERY_2H"
        
        # Every 6 hours
        EVERY_6H=$([[ $((10#$HOUR % 6)) -eq 0 ]] && echo "true" || echo "false")
        run_workflow "bot-management.yml" "$EVERY_6H"
        run_workflow "issue-processor.yml" "$EVERY_6H"
        
        # Daily at 2 AM
        DAILY_2AM=$([[ "$HOUR" == "02" ]] && echo "true" || echo "false")
        run_workflow "security-audit.yml" "$DAILY_2AM"
        run_workflow "cost-report.yml" "$DAILY_2AM"
        run_workflow "ai-research.yml" "$DAILY_2AM"
        run_workflow "dependency-update.yml" "$DAILY_2AM"
        
        # Weekly on Sunday at 3 AM
        WEEKLY_SUNDAY=$([[ "$DAY" == "7" && "$HOUR" == "03" ]] && echo "true" || echo "false")
        run_workflow "batch-production.yml" "$WEEKLY_SUNDAY"
        run_workflow "repo-hygiene.yml" "$WEEKLY_SUNDAY"
        run_workflow "full-security-scan.yml" "$WEEKLY_SUNDAY"
        
        # Monthly on 1st at 4 AM
        MONTHLY=$([[ "$DAY_OF_MONTH" == "01" && "$HOUR" == "04" ]] && echo "true" || echo "false")
        run_workflow "cost-analysis.yml" "$MONTHLY"
        run_workflow "performance-report.yml" "$MONTHLY"
        
        echo "✅ Dispatch complete"
        
    - name: Generate dispatch report
      if: always()
      run: |
        echo "## 📊 Scheduler Report" >> $GITHUB_STEP_SUMMARY
        echo "- Time: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "- Scheduled workflows dispatched based on intelligent routing" >> $GITHUB_STEP_SUMMARY
        echo "- Next run in 1 hour" >> $GITHUB_STEP_SUMMARY
